### ISSUE TITLE
Figure out how to support head movement without attached oculus 

### ISSUE THREAD

**Issue by mroukema** [asweingarten/virtualKeyboard#14]
Currently you need the oculus attached to move the players head up/down. It would be great if we could support this with mouse movement or key bindings when the oculus is not attached.

**Comment by mroukema** [comment]
Binding head movement to the mouse would be ideal

**Comment by eh-dub** [comment]
@tgugoiu can you get this done by end of day friday?

**Comment by tgugoiu** [comment]
Pushed this just now, need input if Y sensitivity needs tweaking

**Comment by mroukema** [comment]
Two things Theo,
1. Can you make this a public variable so we can change it in the GUI
2. Can you do your work on a separate branch so that we can easily test your changes and not make messy merges

**Comment by mroukema** [comment]
Sensitivity seems good to me. 
Changes are compatible with Oculus as well.

**Comment by mroukema** [comment]
Can we make the y-axis mouse tracking toggle able with a hot key? perhaps one of the function keys.
