### ISSUE TITLE
Radial Menu System 

### ISSUE THREAD

**Issue by mroukema** [asweingarten/virtualKeyboard#16]
Deliverable: A reusable prefab component that allows crafting radial menus.

Works with leap motion or with mouse

**Comment by mroukema** [comment]
One demo of this menu could be a colour picker,

For example, on the first level of the menu have _n_ different colours, the next level of the menu could be the shades of that colour and perhaps one more level for alpha

**Comment by eh-dub** [comment]
I'm going to take the D-pad components and try and jerry rig some radial menus with them

**Comment by eh-dub** [comment]
Will also look into the GUI components
