### ISSUE TITLE
Input Prefab Ideas

### ISSUE THREAD

**Issue by mroukema** [asweingarten/virtualKeyboard#7]
So far we have a keyboard prefab. 

Many other input methods may be viable and we should look into creating more of them. 

List ideas in the comments below.

**Comment by mroukema** [comment]
Some ideas from Ariel + Mark:

T9
Lotus
Pure Virtual Keyboard (no physical keyboard required for use) 
Joystick
Inventory Management System (think could we improve minecraft inventory)
Photo Gallery
Colour Picker
Music Composing 
Radial Menu Prefabs

**Comment by eh-dub** [comment]
Closing as we are homing in on the interior decoration idea and have other issues for the prefabs needed for it.
