### ISSUE TITLE
Cannot apply rotations to RadialMenu unless it has already been drawn

### ISSUE THREAD

**Issue by mroukema** [asweingarten/virtualKeyboard#78]
If you try to apply a rotation to the radial menu before it has been drawn the drawing process will end up applying extra rotations/transforms on the individual arc sections resulting in the pieces been separated. 

Work around for now is to draw the radial menu then apply the transforms. 
Added an undrawRadialMenu context menu option to make working with it easier.

**Comment by eh-dub** [comment]
Fixed in c4fc68c41eb7dd5146c3c08b869d4cc8e4143910
