### ISSUE TITLE
When an item is selected, there should be a key press to bring up radial menu

### ISSUE THREAD

**Issue by eh-dub** [asweingarten/virtualKeyboard#89]

**Comment by mroukema** [comment]
It is actually quite difficult to determine when an object has been selected due to the way item manipulation works. A game object on its own cannot know whether it is the selected state, only the root level item manipulator know what item is currently selected.

**Comment by mroukema** [comment]
Basic Implementation included in 280c43eb6cd5331bdd0700e963df8a6d27965d00
